jobs:
  mon_pix_build_and_test:
    executor:
      name: node-browsers-docker
    working_directory: ~/pix/mon-pix
    parallelism: 3
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-mon-pix-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v7-mon-pix-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci

workflows:
  version: 2
  build-and-test:
    jobs:
      - mon_pix_build_and_test:
          context: Pix
          requires:
            - checkout
