jobs:
  api_build_and_test:
    executor:
      name: node-redis-postgres-docker
    working_directory: ~/pix/api
    steps:
      - attach_workspace:
          at: ~/pix
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v7-api-npm-{{ checksum "cachekey" }}
      - run: npm ci --no-optional
      - save_cache:
          key: v7-api-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circleci
            TEST_REDIS_URL: redis://localhost:6379
          when: always
      - run:
          name: Test
          command: npm run test
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circleci
            TEST_REDIS_URL: redis://localhost:6379
            MOCHA_FILE: /home/circleci/test-results/test-results.[hash].xml
            MOCHA_REPORTER: mocha-junit-reporter
          when: always
      - store_test_results:
          path: /home/circleci/test-results
      - store_artifacts:
          path: /home/circleci/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - api_build_and_test:
          context: Pix
          requires:
            - checkout
